# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale: "en-US"
title: "Jadesola Kareem"
title_separator: "|"
name: &name "Jadesola Kareem"
description: &description "Machine Learning Researcher | Community Builder"
url: "https://jadesola123.github.io" # GitHub Pages URL
baseurl: "" # no subpath since this is a user site repo
repository: "jadesola123/jadesola123.github.io"

# Author Profile (sidebar)
author:
  avatar: "profile.png"
  name: "Jadesola Kareem"
  pronouns: "she/her"
  bio: "Machine learning enthusiast exploring emotion recognition, affective computing, and social impact."
  location: "Liverpool, UK"
  employer: "University of Chester"
  uri: ""
  email: "jadesolak.business@gmail.com"

  # Academic websites
  googlescholar: "" # optional, leave blank if you don’t have one
  orcid: ""         # optional

  # Developer & social links
  github: "jadesola123"
  linkedin: "jadesola-kareem"
  speakerdeck: "jadesola123"
  medium: ""        # if you publish articles
  twitter: ""       # optional

# Site behavior
breadcrumbs: false
future: true
read_more: "enabled"
talkmap_link: false

# Comments
comments:
  provider: false

# SEO
google_site_verification: ""
bing_site_verification: ""

# Social Sharing
social:
  type: Person
  name: "Jadesola Kareem"
  links:
    - https://github.com/jadesola123
    - https://www.linkedin.com/in/jadesola-kareem/
    - https://speakerdeck.com/jadesola123

# Analytics (optional)
analytics:
  provider: "false"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Page Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Output Settings
permalink: /:categories/:title/
timezone: Europe/London

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
