title: "Kareem Jadesola"
description: "My Academic Website"
theme: jekyll-theme-minimal
baseurl: "" # Leave empty for root directory
url: "https://jadesola123.github.io" # Replace with your GitHub Pages URL

# Navigation
header_pages:
  - index.md
  - blog.md
  - about.md
  - publications.md
