# _config.yml for Minima Theme

# Site settings
title: "Jadesola's Academic Site"
description: "A space to share my research, projects, and academic insights"
url: "https://jadesola123.github.io"
baseurl: ""  # The base URL for your site, leave as is if it's at the root of your GitHub Pages site.

# Theme settings
theme: minima
theme_prefix: "minima"

# Author information
author:
  name: "Jadesola"
  email: "jadesolak.business@gmail.com"

# Social links (add any social profiles you want to link to)
social_links:
  - label: "GitHub"
    url: "https://github.com/jadesola123"
  - label: "LinkedIn"
    url: "https://linkedin.com/in/jadesola-kareem"
  - label: "Twitter"
    url: "https://twitter.com/jaded_developer"

# Navigation menu items
nav:
  - title: "Blog"
    url: "/blog/blog.md"
  - title: "About Me"
    url: "/about/about.md"
  - title: "Publications"
    url: "/publications/publications.md"

# Exclude files from being published to GitHub Pages
exclude:
  - README.md  # Exclude the readme file from being published
  - LICENSE.md  # Exclude the license file from being published

# Permalinks configuration
permalink: "pretty"  # This setting determines how your URLs will be structured (e.g., /year/month/day/slug/)

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM

# Plugins for adding extra functionality
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Other settings
timezone: "Europe/London"  # Adjust the timezone to match your location
